repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1 # Use the latest ruff-pre-commit version
    hooks:
      - id: ruff
        args: [--fix] # Automatically fix issues
      - id: ruff-format
